---
title: "Exercise 2"
author: "Carilli"
date: '`r format(lubridate::today, "%B %d, %Y")`'
output: 
  html_document:
    theme: cerulean
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, warning = FALSE, message = FALSE,
                      options(digits = 3, scipen = 999))
library(tidyverse)
```

```{r 2data}
fed <- 
  here::here("data", "fed_2012_kkedits.csv") %>% 
  read_csv() %>% 
  janitor::clean_names() %>% 
  rename(quarters = election)
```

### (a)

```{r 2a, message=FALSE, warning=FALSE}
fed %>% 
  mutate(party = factor(democrat, labels = c("Republican", "Democrat"))) %>% 
  ggplot(aes(x = quarters, y = fedfunds)) + 
  geom_point() + 
  geom_smooth(method =lm, se = FALSE) +
  facet_wrap(~ party) 
```

### (b)

```{r 2b}
fed %>% 
  mutate(party = factor(democrat, labels = c("Republican", "Democrat"))) %>% 
  lm(fedfunds ~ quarters*party, .) %>% 
  jtools::summ()
```

#### (i)

```{r 2b_i}
rep_marginal <- 
fed %>% 
  mutate(party = factor(democrat, labels = c("Republican", "Democrat"))) %>% 
  lm(fedfunds ~ quarters*party, .) %>% 
  broom::tidy() %>% 
  pull(estimate)
rep_marginal[2]
```

#### (ii)

```{r 2b_ii}
rep_democrat <- 
fed %>% 
  mutate(party = factor(democrat, labels = c("Republican", "Democrat"))) %>% 
  lm(fedfunds ~ quarters*party, .) %>% 
  broom::tidy() %>% 
  pull(estimate)
rep_democrat[2] + rep_democrat[4]
```

### (c)

```{r 2c}
fed %>% 
  mutate(party = factor(democrat, labels = c("Republican", "Democrat"))) %>% 
  lm(fedfunds ~ quarters*party, .) %>% 
  car::linearHypothesis("quarters + quarters:partyDemocrat = 0")
```

### (d)

```{r 2d, warning=FALSE, message=FALSE}
fed %>% 
  mutate(party = factor(democrat, labels = c("Republican", "Democrat"))) %>% 
  ggplot(aes(x = quarters, y = fedfunds, color = party)) + 
  geom_smooth(method =lm, se = FALSE) +
  labs(x = "Quarters from last election", y = "Federal funds rate")
```

### (e)

```{r 2e}
fed %>% 
  mutate(party = factor(democrat, labels = c("Republican", "Democrat"))) %>% 
  lm(fedfunds ~ quarters*party + inflation + lag(fedfunds), .) %>% 
  jtools::summ()
```

```{r 2e_i}
fed %>% 
  mutate(party = factor(democrat, labels = c("Republican", "Democrat"))) %>% 
  lm(fedfunds ~ quarters*party + inflation + lag(fedfunds), .) %>% 
  car::linearHypothesis("quarters = 0")
```

```{r 2e_ii}
fed %>% 
  mutate(party = factor(democrat, labels = c("Republican", "Democrat"))) %>% 
  lm(fedfunds ~ quarters*party + inflation + lag(fedfunds), .) %>% 
  car::linearHypothesis("quarters + quarters:partyDemocrat = 0")
```

```{r 2e_iii}
fed %>% 
  mutate(party = factor(democrat, labels = c("Republican", "Democrat"))) %>% 
  lm(fedfunds ~ quarters*party + inflation + lag(fedfunds), .) %>% 
  car::linearHypothesis("lag(fedfunds) = 0")
```

```{r 2e_iv}
fed %>% 
  mutate(party = factor(democrat, labels = c("Republican", "Democrat"))) %>% 
  lm(fedfunds ~ quarters*party + inflation + lag(fedfunds), .) %>% 
  car::linearHypothesis("inflation = 0")
```
