---
title: "Exercise 5"
author: "Carilli"
date: '`r format(lubridate::today(), "%B %d, %Y")`'
output: 
  html_document:
    theme: cerulean
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, warning = FALSE, message = FALSE,
                      options(digits = 3, scipen = 999))
library(tidyverse)
```

```{r 5data}
knowledge <- 
  here::here("data", "FiscalPolicy.csv") %>% 
  read_csv() %>% 
  janitor::clean_names()
```

### (a)

```{r 5a}
jtools::export_summs(
  knowledge %>% 
  lm(spend_unemp ~ knowledge_index2, .),
  
  knowledge %>% 
  lm(tax_unemp_correct ~ knowledge_index2, .),
  model.names = c("Spending & Unemployment", "Tax & Unemployment")
)
```

### (b)

```{r 5b}
jtools::export_summs(
  knowledge %>% 
  lm(spend_unemp ~ knowledge_index2 + gop, .),
  
  knowledge %>% 
  lm(tax_unemp_correct ~ knowledge_index2 + gop, .),
  model.names = c("Spending & Unemployment", "Tax & Unemployment")
)
```


### (c)

```{r 5c}
jtools::export_summs(
  knowledge %>% 
  lm(spend_unemp ~ knowledge_index2 * gop, .),
  
  knowledge %>% 
  lm(tax_unemp_correct ~ knowledge_index2 * gop, .),
  model.names = c("Spending & Unemployment", "Tax & Unemployment")
)
```

